### ISSUE TITLE
why do not have the code for ETTDataset

### ISSUE THREAD

**Issue by NewKeyTo** [WenjieDu/SAITS#24]

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Hi,

The experiments conducted on ETT dataset are added lately and additionally to make the reviewer satisfied with the number of datasets used in this work. If you refer to [an earlier version of SAITS paper](https://arxiv.org/pdf/2202.08516v2.pdf), you will see that ETT doesn't exist. 

Will clean the related scripts and add them to this repo. If it doesn't bother you, please star 🌟 this repo to help more people notice this useful work. Thanks.

**Comment by NewKeyTo** [comment]
ok, thank you for your work and reply!

**Comment by WenjieDu** [comment]
Updated. Check out PR #25. Please pay a visit to the toolbox PyPOTS [https://github.com/WenjieDu/PyPOTS](https://github.com/WenjieDu/PyPOTS) if you're interested in modeling partially-observed time series (POTS). It deserves your attention ;-) Please star 🌟 PyPOTS if you like it.
