### ISSUE TITLE
Is this X_tilde_3 or X_c?

### ISSUE THREAD

**Issue by lzylzylllll** [WenjieDu/SAITS#26]
imputation_MAE = masked_mae_cal(
                X_tilde_3, inputs["X_holdout"], inputs["indicating_mask"]
            )

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Yeah, I know this. No worries. The parts in `X_tilde_3` and `X_c` for loss calculation are exactly the same.

**Comment by lzylzylllll** [comment]
Do you mean X_tilde_3 and X_c values are equal?

**Comment by WenjieDu** [comment]
Of course they are not equal, there is code here to generate X_c from X_tilde_3 https://github.com/WenjieDu/SAITS/blob/main/modeling/saits.py#L193-L196. I mean the exactly what I said above `the parts in X_tilde_3 and X_c for this loss calculation are exactly the same`. You can replace `X_tilde_3` with `X_c` in that line of code calculating `imputation_MAE`. The result will be the same.

**Comment by lzylzylllll** [comment]
I understand, thanks for the answer

**Comment by WenjieDu** [comment]
Absolutely my pleasure. If it doesn't bother you, please star 🌟 this repo to help more people notice this useful work. Thanks.

**Comment by WenjieDu** [comment]
I'm closing this issue due to all questions solved. BTW, if you're interested in time series modeling, PyPOTS may be useful to you. Please pay a visit to https://pypots.com/ to know more about it. 😊
