### ISSUE TITLE
Can this be implemented to single feature time series dataset?

### ISSUE THREAD

**Issue by jkim50104** [WenjieDu/SAITS#29]
I'm trying to impute a single feature dataset. Can it be possible?

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Surely yes you can.

**Comment by jkim50104** [comment]
Would the performance still be reliable?

**Comment by WenjieDu** [comment]
Why not star this repo and give it a try? With [PyPOTS](https://github.com/WenjieDu/PyPOTS/), you can simply run SAITS on your dataset.
