### ISSUE TITLE
missing value problems

### ISSUE THREAD

**Issue by longjihuang** [WenjieDu/SAITS#3]

**Comment by longjihuang** [comment]
how to solve the missing value's similairty computation? for example, x[1..10] are the missing time series, how to compute the similarity of x[1] and x[2] or other missing values?
Thanks for  your answers, this is a puzzle for me.

**Comment by WenjieDu** [comment]
Hi @longjihuang , I'm sorry. I do not quite understand your question. What do you mean by missing value's similarity? And in your example "x[1..10] is the missing time series", do you mean, as a time-series sample, x has 10 time-steps (i.e. sequence length=10)? It's confusing. Could you explain in detail? Thanks.

**Comment by WenjieDu** [comment]
Closed it due to no response from the issue raiser.
