### ISSUE TITLE
Question about hyperparameter optimization

### ISSUE THREAD

**Issue by SilenceRan** [WenjieDu/SAITS#33]
Hello, I would like to ask you about the hyperparameter optimization for the model. In your file NNI_tuning/SAITS/SAITS_searching_config.yml, you described the settings for the hyperparameters and the training command, which also includes a JSON file. However, when I tried to run the command for hyperparameter optimization on SAITS, I encountered an error: "No option 'mit' in section: 'training'". I supplemented the missing parameters and ran it again, but I only obtained the parameters set in the SAITS_basic_config.ini file. Could you please advise me on how to iterate through the parameters in the JSON file to obtain the optimal parameters?

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
What do you mean by "only obtained the parameters set in the SAITS_basic_config.ini file"?

**Comment by SilenceRan** [comment]
What method do you use to optimize the parameters of SAITS?

**Comment by WenjieDu** [comment]
对不起，我实在看不懂你上面的英文描述，我看到你在你自己的repo中使用了中文描述，所以我推测你应该会中文，让我们用中文交流吧，请使用中文描述你的遇到的问题，如果遇到文件名/代码/命令行，请最起码使用引号与你的描述进行分割，提问者所应具备的最起码的素质就是将自己的问题以清晰的逻辑描述清楚，谢谢。

**Comment by SilenceRan** [comment]
抱歉，现在才回复您的消息，我想问一下，SAITS模型有那么多可调的参数，您是使用什么方法将这些参数调整到最优的？

**Comment by WenjieDu** [comment]
没事。关于超参优化的部分，readme中已经说了是使用的NNI进行超参搜索的，各个模型在实验中的NNI配置文件也全都给出了，如果不熟悉NNI请先了解一下学习如何使用 https://github.com/microsoft/nni

**Comment by SilenceRan** [comment]
感谢回答，我去学习一下，您的SAITS模型十分优秀，使我受益匪浅！

**Comment by WenjieDu** [comment]
不客气，谢谢你对SAITS这篇论文的认可，如果喜欢，请给我们这个代码仓库加个星⭐️，请在你的工作中引用我们的工作，非常感谢！如果你的工作与不完整的时序相关，https://github.com/WenjieDu/PyPOTS或许对你有帮助。你也可以在github上关注我，及时了解我们团队最新的开源动态。

**Comment by lyli17** [comment]
> 感谢回答，我去学习一下，您的SAITS模型十分优秀，使我受益匪浅！

你好，想请问一下你在跑这个代码的时候可视化是否出现了生成的数据与原始数据一样的问题，可以帮忙看看吗，我现在有这个困扰
