### ISSUE TITLE
Question about output of the first DMSA

### ISSUE THREAD

**Issue by miten073** [WenjieDu/SAITS#35]
Hello, I want to ask you about the saits.py part of the modeling in your code, I only used the first DMSA module, I also entered the X and Miss Mask in your way, but after going through the encoder layer, data becomes all Nan, what is the reason for this situation.
Looking forward to your reply

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by miten073** [comment]
Thank you for your answer, but my question still exists, I suspect my input is wrong.
1. Is the 'x' of the module that entered the first DMSA block the original input data that contains the nan value?
2.does the 'miss_mask' mark the observed value as 1 and the missing value as 0?
3.If the input is correct, and after the embedding layers, the lines containing 'nan' will all become 'nan', what should I do with it?
Looking forward to your answer
