### ISSUE TITLE
关于生成数据的一些问题

### ISSUE THREAD

**Issue by V50-ikun** [WenjieDu/SAITS#38]
您好，在代码复现过程中遇到了一些问题，希望您能解答。
1.插补生成的数据与原始数据一样，在ETT测试集中，根据missing_mask可以得知(0,3)这个点应该是手动缺失，但最后生成的值和原始值一摸一样，excel是数据标准化后导出的文件，h5文件是生成的文件。
![Snipaste_2024-06-03_14-56-24](https://github.com/WenjieDu/SAITS/assets/131343367/2b9ff760-3ec6-4f30-9bdc-229ecc6f4fbc)

2.如果采用自己的数据集，训练过程中的config文件是要自己定义吗？其次config文件夹中的best是自己不断训练出来的吗？

3.最后插补生成的h5文件我想用来进行下游预测工作，可以转为csv导出吗？

**Comment by lyli17** [comment]
> 您好，在代码复现过程中遇到了一些问题，希望您能解答。 1.插补生成的数据与原始数据一样，在ETT测试集中，根据missing_mask可以得知（0,3）这个点应该是手动缺失，但最后生成的值和原始值一摸一样，excel是数据标准化后导出的文件，h5文件是生成的文件。 ![Snipaste_2024-06-03_14-56-24](https://github.com/WenjieDu/SAITS/assets/131343367/2b9ff760-3ec6-4f30-9bdc-229ecc6f4fbc)
> 
> 2.如果采用自己的数据集，训练过程中的config文件是要自己定义吗？其次config文件夹中的best是自己不断训练出来的吗？
> 
> 3.最后插补生成的h5文件我想用来进行下游预测工作，可以转为csv导出吗？



> 您好，在代码复现过程中遇到了一些问题，希望您能解答。 1.插补生成的数据与原始数据一样，在ETT测试集中，根据missing_mask可以得知(0,3)这个点应该是手动缺失，但最后生成的值和原始值一摸一样，excel是数据标准化后导出的文件，h5文件是生成的文件。 ![Snipaste_2024-06-03_14-56-24](https://github.com/WenjieDu/SAITS/assets/131343367/2b9ff760-3ec6-4f30-9bdc-229ecc6f4fbc)
> 
> 2.如果采用自己的数据集，训练过程中的config文件是要自己定义吗？其次config文件夹中的best是自己不断训练出来的吗？
> 
> 3.最后插补生成的h5文件我想用来进行下游预测工作，可以转为csv导出吗？

您好，我在代码复现ETT数据集的时候也遇到了跟你所描述的第一点里一样的问题，插补的数据和原始数据一样，请问你后面解决了吗

**Comment by zhengcheng704** [comment]
> > 您好，在代码复现过程中遇到了一些问题，希望您能解答。 1.插补生成的数据与原始数据一样，在ETT测试集中，根据missing_mask可以得知（0,3）这个点应该是手动缺失，但最后生成的值和原始值一摸一样，excel是数据标准化后导出的文件，h5文件是生成的文件。 ![Snipaste_2024-06-03_14-56-24](https://github.com/WenjieDu/SAITS/assets/131343367/2b9ff760-3ec6-4f30-9bdc-229ecc6f4fbc)
> > 2.如果采用自己的数据集，训练过程中的config文件是要自己定义吗？其次config文件夹中的best是自己不断训练出来的吗？
> > 3.最后插补生成的h5文件我想用来进行下游预测工作，可以转为csv导出吗？
> 
> > 您好，在代码复现过程中遇到了一些问题，希望您能解答。 1.插补生成的数据与原始数据一样，在ETT测试集中，根据missing_mask可以得知(0,3)这个点应该是手动缺失，但最后生成的值和原始值一摸一样，excel是数据标准化后导出的文件，h5文件是生成的文件。 ![Snipaste_2024-06-03_14-56-24](https://github.com/WenjieDu/SAITS/assets/131343367/2b9ff760-3ec6-4f30-9bdc-229ecc6f4fbc)
> > 2.如果采用自己的数据集，训练过程中的config文件是要自己定义吗？其次config文件夹中的best是自己不断训练出来的吗？
> > 3.最后插补生成的h5文件我想用来进行下游预测工作，可以转为csv导出吗？
> 
> 您好，我在代码复现ETT数据集的时候也遇到了跟你所描述的第一点里一样的问题，插补的数据和原始数据一样，请问你后面解决了吗

只有训练集有插补数据，测试集和原始数据一样的，我也是这个问题
