### ISSUE TITLE
Inquiry About Using SAITS Model with 'physionet_2012' Dataset

### ISSUE THREAD

**Issue by Huozhiyuan** [WenjieDu/SAITS#41]
Hi everyone:

While using the 'physionet_2012' dataset, I found that the 'y' values cannot be output as expected. I noticed that the article's 'Downstream classification task' section addresses relevant content. If the 'In-hospital_death' values are not 0 and 1 but some other numbers, and the 'X' section content influences the mortality rate, can the SAITS model be used to predict this? If so, which function of SAITS should I use?

Thank you for your assistance.

Best regards,

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
@Rajesh90123 Here is the script running a simple RNN on the downstream classification task https://github.com/WenjieDu/SAITS/blob/main/Simple_RNN_on_imputed_data.py

Regarding the Awesome_Imputation repo, we'll add the downstream task scripts recently. Stay tuned, please! You can star and watch it to receive the latest updates ;-) https://github.com/WenjieDu/Awesome_Imputation
