### ISSUE TITLE
using Additional signal as second feature to improve the imputation of first signal

### ISSUE THREAD

**Issue by MehdiBejani** [WenjieDu/SAITS#43]
Hi,

I'm working on imputing missing values in a set of eye movement signals where participants are following a target. Unfortunately, the imputation results I'm getting with the SAITS model aren't as expected—I'm seeing some jumps and inconsistencies in the missing intervals.

To address this, I tried incorporating the target signal into the SAITS model as a second feature, hoping that it would help guide the imputation in the missing regions of the eye movement signals. Specifically, I used the following setup:

saits = SAITS(n_steps=500, n_features=2, n_layers=2, d_model=256, n_heads=4, d_k=64, d_v=64, d_ffn=128, dropout=0.2, epochs=150)

Unfortunately, even with the additional target signal, the imputation quality hasn’t improved as much as I hoped, and I’m still encountering jumps in the missing intervals.

Here are my questions:
1. Do you have any suggestions for improving the imputation quality? Is there a specific way I should be handling the relationship between the eye movement and target signals to get better results?
2. Should the signals be normalized before feeding them into the SAITS model? I’ve seen you use `StandardScaler()`, but I’m also considering using `MinMaxScaler()`.
3. Are there any other parameters or aspects of the SAITS model that I could adjust to improve performance for this type of data?

I appreciate any help or guidance you can provide.

Thank you!

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie
